<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="canonical" href="https://www.oswaldocruz.br/default.asp" />

    <!-- CSS -->
    <link rel="stylesheet" href="../RESOURCES/CSS/estilo.css" />
    <link rel="stylesheet" href="../RESOURCES/CSS/bootstrapFoc.min.css" />
    <link defer rel="stylesheet" href="../RESOURCES/CSS/glyphicon.css" />

    <!-- Fonte e Ícone -->
    <link defer rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round" />
    <link defer rel="shortcut icon" href="../RESOURCES/IMGS/logos/favicon1.png" />

    <!-- Scripts -->
    <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js"></script>
    <script src="../RESOURCES/JS/jquery-3.3.1.slim.min.js"></script>
    <script src="../RESOURCES/JS/jquery-3.3.1.min.js"></script>
    <script src="../RESOURCES/JS/popper.min.js"></script>
    <script src="../RESOURCES/JS/bootstrap.min.js"></script>
    <script defer type="text/javascript" src="../RESOURCES/JS/main.js"></script>