<div class="footer-copyright text-center py-3 text-white" style="background-color: rgb(0, 30, 62);">
            Copyright 2002-2019©. Todos os direitos reservados.
            <p><small>Os conteúdos aqui publicados são de responsabilidade de seus autores, não refletindo,
            necessariamente, a opinião da instituição.</small> </p>
            <p><a href="default.asp" class="text-white">Faculdades Oswaldo Cruz</a> |
                <a href="https://www.oswaldocruz.br/equipe/equipe_web.asp" class="text-white" 
                    target="_blank">Equipe Web</a>
            </p>
        </div>