<nav class="navbar navbar-expand-lg navbar-default navbar-light">
        <div class="container">

            <a class="navbar-brand" href="default.asp">
                <img src="../RESOURCES/IMGS/logos/logoAzulFundoBrancoHorizontal.jpg" alt="Logo azul escrito Faculdades Oswaldo Cruz">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto menu-header">

                    <li class="nav-item active">
                        <a class="nav-link" href="default.asp" style="color: rgb(0, 30, 62)">Pagina Inicial</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="https://www.oswaldocruz.br/vestibular/">Processo Seletivo</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="https://www.consultebolsas.com.br/">Bolsas e Descontos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="colegio.asp">Colégio</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="oswaldoCruz.asp">Institucional</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>